basic.showString(control.deviceName())
basic.showIcon(IconNames.Heart)
basic.forever(function () {
    cuteBot.forward()
    basic.pause(200)
    cuteBot.motors(10, 4)
    basic.showArrow(ArrowNames.West)
    basic.pause(1000)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.motors(4, 10)
    basic.showArrow(ArrowNames.East)
    basic.pause(1000)
    cuteBot.forward()
    basic.pause(200)
})
